### PR TITLE
Generic nest label

### PR DESCRIPTION
**Pull request by michalgawliksas**
Generic option for split command that allow to create nested folders based on provided label value.

### CODE REVIEW

**Comment by hornpolish** [comment]
Hi Michael -- thanks for the contribution.  Do you think you can include a test for this?  It doesnt have to be SAS yaml, but it should test for something similar.  I'm back from vacay in April, so can help you with a test case then...  paul

**Comment by michalgawliksas** [comment]
Hi Paul,

sure. I’ll add test case.
Stay safe and have a great vacation 😊

Best,
Michał

**Comment by hornpolish** [comment]
cool. sorry about spelling yr name wrong.. my middle name is michael with the e and my fingers type that automatically 🤡. i’ll try to do better!


[Sorry if this was terse. It was pecked into a handset.  Paul.]

**Comment by michalgawliksas** [comment]
I'm closing this one to open new with additional test cases.

**Pull request closed without merging**
